application: benhymers
version: 3
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /favicon.ico
  script: empty_favicon.py

- url: /apple-touch-icon.png
  script: empty_favicon.py

- url: /apple-touch-icon-precomposed.png
  script: empty_favicon.py

- url: /_ah/queue/deferred
  script: deferred.py
  login: admin

- url: /admin/.*
  script: admin.py
  login: admin

- url: /static/([^/]+)/(.*)
  static_files: themes/\1/static/\2
  upload: themes/[^/]+/static/.*

- url: /.*
  script: static.py
